apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring-boot
spec:
  selector:
    matchLabels:
      app: spring-boot
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: ten
          ports:
            - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec: 
  type: Nodeport
  selector:
     app: spring-boot
  ports:
   port: 80
   targetPort: 8080
   type: LoadBalancer